name: Auto

on:
  schedule:
    - cron: "30 22 * * *" # 北京时间上午06:30
  workflow_dispatch:

env:
  COOKIE: ${{ '__tea_cookie_tokens_2608=%257B%2522web_id%2522%253A%25227264406375111165440%2522%252C%2522user_unique_id%2522%253A%25227264406375111165440%2522%252C%2522timestamp%2522%253A1691376434415%257D; n_mh=zZgm57pXJ9eU1op-6-gPBKq0dTvW4KJntl42JmCxz_c; store-region=cn-zj; store-region-src=uid; _tea_utm_cache_2608={%22utm_source%22:%22gold_browser_extension%22}; PPA_CI=025df5bc0485ce29e8f3492aa396f700; csrf_session_id=454a7b7adacdc2e713deaa5622159537; passport_csrf_token=e183f35c4c192dad6ff6bb6ccaf1d34a; passport_csrf_token_default=e183f35c4c192dad6ff6bb6ccaf1d34a; msToken=TyUHjsRlSzT_QuhsB4zBDrgg6QepoKKR1FHq86hXGZXTCP-UbSzke99lZTAt1EKxZP4pyh-f-csbZ13ZTn7bYd2XqLdA9VH-1x8tq3HxbqCiCzAKMyNbntIBLVku830=; passport_auth_status=105ed5cd0119b4864aa1a9b7a69848b3%2C; passport_auth_status_ss=105ed5cd0119b4864aa1a9b7a69848b3%2C; sid_guard=e9c5c1b91002ca21a3e5a73d9961361f%7C1701076018%7C31536000%7CTue%2C+26-Nov-2024+09%3A06%3A58+GMT; uid_tt=861ee6e1cea2446b3d8f84e18f4935cd; uid_tt_ss=861ee6e1cea2446b3d8f84e18f4935cd; sid_tt=e9c5c1b91002ca21a3e5a73d9961361f; sessionid=e9c5c1b91002ca21a3e5a73d9961361f; sessionid_ss=e9c5c1b91002ca21a3e5a73d9961361f; sid_ucp_v1=1.0.0-KGM1MDEyMTg3OWMwZDQzZGRhMzA3MWYwM2NkMzlmZTYxNTE3YjI0NzUKFwj-qICt9fWfAhCyuJGrBhiwFDgCQPEHGgJsZiIgZTljNWMxYjkxMDAyY2EyMWEzZTVhNzNkOTk2MTM2MWY; ssid_ucp_v1=1.0.0-KGM1MDEyMTg3OWMwZDQzZGRhMzA3MWYwM2NkMzlmZTYxNTE3YjI0NzUKFwj-qICt9fWfAhCyuJGrBhiwFDgCQPEHGgJsZiIgZTljNWMxYjkxMDAyY2EyMWEzZTVhNzNkOTk2MTM2MWY' }}
  COOKIE_2: ${{ secrets.COOKIE_2 }}
  COOKIE_3: ${{ secrets.COOKIE_3 }}
  COOKIE_4: ${{ secrets.COOKIE_4 }}
  COOKIE_5: ${{ secrets.COOKIE_5 }}
  EMAIL_USER: ${{ secrets.EMAIL_USER }}
  EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
  EMAIL_TO: ${{ secrets.EMAIL_TO }}
  DINGDING_WEBHOOK: ${{ 'https://oapi.dingtalk.com/robot/send?access_token=31a376eea2cc129c92edf03200ef8b7b6ebb5380e29db3c7ac45fbf2c638068d' }}
  PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
  WEIXIN_WEBHOOK: ${{ secrets.WEIXIN_WEBHOOK }}
  SERVERPUSHKEY: ${{ secrets.SERVERPUSHKEY }}

jobs:
  CheckIn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Run Project
        run: |
          cd workflows
          yarn
          yarn checkin
#  SeaGold:
#    needs: CheckIn
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-node@v2
#      - name: Run Project
#        run: |
#          cd workflows
#          yarn
#          yarn seagold
