name: Auto

on:
  schedule:
    - cron: "30 22 * * *" # 北京时间上午06:30
  workflow_dispatch:

env:
  COOKIE: ${{ '__tea_cookie_tokens_2608=%257B%2522web_id%2522%253A%25227212459438991787559%2522%252C%2522user_unique_id%2522%253A%25227212459438991787559%2522%252C%2522timestamp%2522%253A1679281585733%257D; n_mh=zZgm57pXJ9eU1op-6-gPBKq0dTvW4KJntl42JmCxz_c; store-region-src=uid; _tea_utm_cache_2608={%22utm_source%22:%22gold_browser_extension%22}; _tea_utm_cache_4366={%22utm_medium%22:%22banner%22%2C%22utm_campaign%22:%22rgznqy202305%22}; csrf_session_id=dfb3dd2cfd7ecd412e8a65821a9c7ae9; passport_csrf_token=312a8ae7a1692738b3a7b409d7ddbba3; passport_csrf_token_default=312a8ae7a1692738b3a7b409d7ddbba3; passport_auth_status=01c4fbf5fc67716796ed60af48d80e4a%2C; passport_auth_status_ss=01c4fbf5fc67716796ed60af48d80e4a%2C; sid_guard=de0fc6ef534fd556ebf02dae26250582%7C1688352228%7C31536000%7CTue%2C+02-Jul-2024+02%3A43%3A48+GMT; uid_tt=c1ee24b56348888d14a71017fe8a302a; uid_tt_ss=c1ee24b56348888d14a71017fe8a302a; sid_tt=de0fc6ef534fd556ebf02dae26250582; sessionid=de0fc6ef534fd556ebf02dae26250582; sessionid_ss=de0fc6ef534fd556ebf02dae26250582; sid_ucp_v1=1.0.0-KDczNTU2MTFhOGIwZDFlNDc5OTAxNGE1YmJlZGJjZWI5MWRjOGZkZTYKFwj-qICt9fWfAhDk64ilBhiwFDgCQPEHGgJsZiIgZGUwZmM2ZWY1MzRmZDU1NmViZjAyZGFlMjYyNTA1ODI; ssid_ucp_v1=1.0.0-KDczNTU2MTFhOGIwZDFlNDc5OTAxNGE1YmJlZGJjZWI5MWRjOGZkZTYKFwj-qICt9fWfAhDk64ilBhiwFDgCQPEHGgJsZiIgZGUwZmM2ZWY1MzRmZDU1NmViZjAyZGFlMjYyNTA1ODI; store-region=cn-zj; msToken=pBK3XJsPr1ZzvN9y2kZUrOl3w2PoQV8b9bnTa-aEDczhL1b-CBnRLJHX1qqZ3MJUEXfk9cO60gYDsKlds7JImfo2XE7SL8K0deaiKyo8ZhD90pjlQqhhIebDK-ejEfk=' }}
  COOKIE_2: ${{ secrets.COOKIE_2 }}
  COOKIE_3: ${{ secrets.COOKIE_3 }}
  COOKIE_4: ${{ secrets.COOKIE_4 }}
  COOKIE_5: ${{ secrets.COOKIE_5 }}
  EMAIL_USER: ${{ secrets.EMAIL_USER }}
  EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
  EMAIL_TO: ${{ secrets.EMAIL_TO }}
  DINGDING_WEBHOOK: ${{ 'https://oapi.dingtalk.com/robot/send?access_token=31a376eea2cc129c92edf03200ef8b7b6ebb5380e29db3c7ac45fbf2c638068d' }}
  PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
  WEIXIN_WEBHOOK: ${{ secrets.WEIXIN_WEBHOOK }}
  SERVERPUSHKEY: ${{ secrets.SERVERPUSHKEY }}

jobs:
  CheckIn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Run Project
        run: |
          cd workflows
          yarn
          yarn checkin
#  SeaGold:
#    needs: CheckIn
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-node@v2
#      - name: Run Project
#        run: |
#          cd workflows
#          yarn
#          yarn seagold
