name: Auto

on:
  schedule:
    - cron: "30 22 * * *" # 北京时间上午06:30
  workflow_dispatch:

env:
  COOKIE: ${{ '__tea_cookie_tokens_2608=%257B%2522web_id%2522%253A%25227212459438991787559%2522%252C%2522user_unique_id%2522%253A%25227212459438991787559%2522%252C%2522timestamp%2522%253A1679281585733%257D; passport_csrf_token=49528692de648fe355c30b8102a6c976; passport_csrf_token_default=49528692de648fe355c30b8102a6c976; n_mh=zZgm57pXJ9eU1op-6-gPBKq0dTvW4KJntl42JmCxz_c; store-region=cn-hb; store-region-src=uid; _tea_utm_cache_2608={%22utm_source%22:%22gold_browser_extension%22}; csrf_session_id=e80079ab02d7c8afe6e57e250f57c105; passport_auth_status=452008749861647109cfe1dca3c27e09%2C; passport_auth_status_ss=452008749861647109cfe1dca3c27e09%2C; sid_guard=e65d7eef13721d3d269dcd353f1e953e%7C1682654427%7C31536000%7CSat%2C+27-Apr-2024+04%3A00%3A27+GMT; uid_tt=3a9548cdcefc8571d4727a50a200392b; uid_tt_ss=3a9548cdcefc8571d4727a50a200392b; sid_tt=e65d7eef13721d3d269dcd353f1e953e; sessionid=e65d7eef13721d3d269dcd353f1e953e; sessionid_ss=e65d7eef13721d3d269dcd353f1e953e; sid_ucp_v1=1.0.0-KDJiODRlYTdmOWY4MmRiOTI0YjkwNmVhZWFmN2M3N2RiMzI5MzhkOTcKFwj-qICt9fWfAhDbia2iBhiwFDgCQPEHGgJsZiIgZTY1ZDdlZWYxMzcyMWQzZDI2OWRjZDM1M2YxZTk1M2U; ssid_ucp_v1=1.0.0-KDJiODRlYTdmOWY4MmRiOTI0YjkwNmVhZWFmN2M3N2RiMzI5MzhkOTcKFwj-qICt9fWfAhDbia2iBhiwFDgCQPEHGgJsZiIgZTY1ZDdlZWYxMzcyMWQzZDI2OWRjZDM1M2YxZTk1M2U' }}
  COOKIE_2: ${{ secrets.COOKIE_2 }}
  COOKIE_3: ${{ secrets.COOKIE_3 }}
  COOKIE_4: ${{ secrets.COOKIE_4 }}
  COOKIE_5: ${{ secrets.COOKIE_5 }}
  EMAIL_USER: ${{ secrets.EMAIL_USER }}
  EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
  EMAIL_TO: ${{ secrets.EMAIL_TO }}
  DINGDING_WEBHOOK: ${{ 'https://oapi.dingtalk.com/robot/send?access_token=31a376eea2cc129c92edf03200ef8b7b6ebb5380e29db3c7ac45fbf2c638068d' }}
  PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
  WEIXIN_WEBHOOK: ${{ secrets.WEIXIN_WEBHOOK }}
  SERVERPUSHKEY: ${{ secrets.SERVERPUSHKEY }}

jobs:
  CheckIn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Run Project
        run: |
          cd workflows
          yarn
          yarn checkin
#  SeaGold:
#    needs: CheckIn
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-node@v2
#      - name: Run Project
#        run: |
#          cd workflows
#          yarn
#          yarn seagold
