name: Auto

on:
  schedule:
    - cron: "30 22 * * *" # 北京时间上午06:30
  workflow_dispatch:

env:
  COOKIE: ${{ '__tea_cookie_tokens_2608=%257B%2522web_id%2522%253A%25227443637662294591028%2522%252C%2522user_unique_id%2522%253A%25227443637662294591028%2522%252C%2522timestamp%2522%253A1733106975362%257D; passport_csrf_token=8e71e56bbf15233bea7a63736e9ff05b; passport_csrf_token_default=8e71e56bbf15233bea7a63736e9ff05b; n_mh=zZgm57pXJ9eU1op-6-gPBKq0dTvW4KJntl42JmCxz_c; is_staff_user=false; store-region=cn-zj; store-region-src=uid; _tea_utm_cache_2018={%22utm_source%22:%22practice%22%2C%22utm_medium%22:%22dailynewtask%22%2C%22utm_campaign%22:%22jjmesg%22}; _tea_utm_cache_2608={%22utm_source%22:%22pop_center%22%2C%22utm_medium%22:%22web_entrance%22%2C%22utm_campaign%22:%22annual_2024%22}; csrf_session_id=518559643ea1b3f1d415182b36f428a0; passport_auth_status=fdf3c564cd7bb0ab7dc98da5df3de92a%2C; passport_auth_status_ss=fdf3c564cd7bb0ab7dc98da5df3de92a%2C; sid_guard=ab74267ee2deb79e851aca6cacced971%7C1737076777%7C31536000%7CSat%2C+17-Jan-2026+01%3A19%3A37+GMT; uid_tt=00e3ec13df812b2cc6d7f463c5eae0b1; uid_tt_ss=00e3ec13df812b2cc6d7f463c5eae0b1; sid_tt=ab74267ee2deb79e851aca6cacced971; sessionid=ab74267ee2deb79e851aca6cacced971; sessionid_ss=ab74267ee2deb79e851aca6cacced971; sid_ucp_v1=1.0.0-KDFmMDFjYjIwZGIxYmQzN2Q3Yjk1M2U3MjE5YzY4Y2QzNGU4OTkxOGIKFwj-qICt9fWfAhCp4Ka8BhiwFDgCQPEHGgJsZiIgYWI3NDI2N2VlMmRlYjc5ZTg1MWFjYTZjYWNjZWQ5NzE; ssid_ucp_v1=1.0.0-KDFmMDFjYjIwZGIxYmQzN2Q3Yjk1M2U3MjE5YzY4Y2QzNGU4OTkxOGIKFwj-qICt9fWfAhCp4Ka8BhiwFDgCQPEHGgJsZiIgYWI3NDI2N2VlMmRlYjc5ZTg1MWFjYTZjYWNjZWQ5NzE' }}
  COOKIE_2: ${{ secrets.COOKIE_2 }}
  COOKIE_3: ${{ secrets.COOKIE_3 }}
  COOKIE_4: ${{ secrets.COOKIE_4 }}
  COOKIE_5: ${{ secrets.COOKIE_5 }}
  EMAIL_USER: ${{ secrets.EMAIL_USER }}
  EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
  EMAIL_TO: ${{ secrets.EMAIL_TO }}
  DINGDING_WEBHOOK: ${{ 'https://oapi.dingtalk.com/robot/send?access_token=31a376eea2cc129c92edf03200ef8b7b6ebb5380e29db3c7ac45fbf2c638068d' }}
  PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
  WEIXIN_WEBHOOK: ${{ secrets.WEIXIN_WEBHOOK }}
  SERVERPUSHKEY: ${{ secrets.SERVERPUSHKEY }}
  FEISHU_WEBHOOK: ${{ secrets.FEISHU_WEBHOOK }}

jobs:
  CheckIn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Run Project
        run: |
          cd workflows
          yarn
          yarn checkin

#  SeaGold:
#    needs: CheckIn
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-node@v2
#      - name: Run Project
#        run: |
#          cd workflows
#          yarn
#          yarn seagold
