name: Auto

on:
  schedule:
    - cron: "30 22 * * *" # 北京时间上午06:30
  workflow_dispatch:

env:
  COOKIE: ${{ '__tea_cookie_tokens_2608=%257B%2522web_id%2522%253A%25227404658410085910035%2522%252C%2522user_unique_id%2522%253A%25227404658410085910035%2522%252C%2522timestamp%2522%253A1724031321298%257D; n_mh=zZgm57pXJ9eU1op-6-gPBKq0dTvW4KJntl42JmCxz_c; is_staff_user=false; store-region=cn-zj; store-region-src=uid; csrf_session_id=91ca35319c105862c0a4d70539759a8a; passport_csrf_token=6f17a6019d5bb41a94a370236689b5a4; passport_csrf_token_default=6f17a6019d5bb41a94a370236689b5a4; passport_auth_status=3b3329d2385e4fbde7f1c71cb8654f22%2C; passport_auth_status_ss=3b3329d2385e4fbde7f1c71cb8654f22%2C; sid_guard=bae3afea7edca3f8275075c5c1a97b49%7C1730443345%7C31536000%7CSat%2C+01-Nov-2025+06%3A42%3A25+GMT; uid_tt=1f1f78c487bba70347d46dec8ad4da30; uid_tt_ss=1f1f78c487bba70347d46dec8ad4da30; sid_tt=bae3afea7edca3f8275075c5c1a97b49; sessionid=bae3afea7edca3f8275075c5c1a97b49; sessionid_ss=bae3afea7edca3f8275075c5c1a97b49; sid_ucp_v1=1.0.0-KDJiMTI3NDllZGNiMDM2YTAyYzBkNzJiYTc3NWE4OTk5NmE5ZDA0MDAKFwj-qICt9fWfAhDR8JG5BhiwFDgCQPEHGgJscSIgYmFlM2FmZWE3ZWRjYTNmODI3NTA3NWM1YzFhOTdiNDk; ssid_ucp_v1=1.0.0-KDJiMTI3NDllZGNiMDM2YTAyYzBkNzJiYTc3NWE4OTk5NmE5ZDA0MDAKFwj-qICt9fWfAhDR8JG5BhiwFDgCQPEHGgJscSIgYmFlM2FmZWE3ZWRjYTNmODI3NTA3NWM1YzFhOTdiNDk' }}
  COOKIE_2: ${{ secrets.COOKIE_2 }}
  COOKIE_3: ${{ secrets.COOKIE_3 }}
  COOKIE_4: ${{ secrets.COOKIE_4 }}
  COOKIE_5: ${{ secrets.COOKIE_5 }}
  EMAIL_USER: ${{ secrets.EMAIL_USER }}
  EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
  EMAIL_TO: ${{ secrets.EMAIL_TO }}
  DINGDING_WEBHOOK: ${{ 'https://oapi.dingtalk.com/robot/send?access_token=31a376eea2cc129c92edf03200ef8b7b6ebb5380e29db3c7ac45fbf2c638068d' }}
  PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
  WEIXIN_WEBHOOK: ${{ secrets.WEIXIN_WEBHOOK }}
  SERVERPUSHKEY: ${{ secrets.SERVERPUSHKEY }}
  FEISHU_WEBHOOK: ${{ secrets.FEISHU_WEBHOOK }}

jobs:
  CheckIn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Run Project
        run: |
          cd workflows
          yarn
          yarn checkin

#  SeaGold:
#    needs: CheckIn
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-node@v2
#      - name: Run Project
#        run: |
#          cd workflows
#          yarn
#          yarn seagold
