name: Auto

on:
  schedule:
    - cron: "30 22 * * *" # 北京时间上午06:30
  workflow_dispatch:

env:
  COOKIE: ${{ '__tea_cookie_tokens_2608=%257B%2522web_id%2522%253A%25227264406375111165440%2522%252C%2522user_unique_id%2522%253A%25227264406375111165440%2522%252C%2522timestamp%2522%253A1691376434415%257D; passport_csrf_token=4f8919c1a81f21af3f03caf83f821075; passport_csrf_token_default=4f8919c1a81f21af3f03caf83f821075; n_mh=zZgm57pXJ9eU1op-6-gPBKq0dTvW4KJntl42JmCxz_c; store-region=cn-zj; store-region-src=uid; PPA_CI=3a377aee895f435c3823a677b64868d4; csrf_session_id=e5150a6bc3bbf8908172fde12cda3cd7; passport_auth_status=dd07d1f6b4f7dc2fd5b7cbd79e804add%2Cbd7f30a6ac46337aa823cd63f3fa743b; passport_auth_status_ss=dd07d1f6b4f7dc2fd5b7cbd79e804add%2Cbd7f30a6ac46337aa823cd63f3fa743b; sid_guard=91c24ee10a921c1417c98a18f966bdfd%7C1693381880%7C31536000%7CThu%2C+29-Aug-2024+07%3A51%3A20+GMT; uid_tt=b11259bf35cc3d41fc4d18e17814a392; uid_tt_ss=b11259bf35cc3d41fc4d18e17814a392; sid_tt=91c24ee10a921c1417c98a18f966bdfd; sessionid=91c24ee10a921c1417c98a18f966bdfd; sessionid_ss=91c24ee10a921c1417c98a18f966bdfd; sid_ucp_v1=1.0.0-KGFhMTA1Nzc2MjcxNDMxYzdlN2M1OTMwNzVjZjg4NTQzNDQ2NTg0MDAKFwj-qICt9fWfAhD46bunBhiwFDgCQPEHGgJobCIgOTFjMjRlZTEwYTkyMWMxNDE3Yzk4YTE4Zjk2NmJkZmQ; ssid_ucp_v1=1.0.0-KGFhMTA1Nzc2MjcxNDMxYzdlN2M1OTMwNzVjZjg4NTQzNDQ2NTg0MDAKFwj-qICt9fWfAhD46bunBhiwFDgCQPEHGgJobCIgOTFjMjRlZTEwYTkyMWMxNDE3Yzk4YTE4Zjk2NmJkZmQ; msToken=UtK0Y0qpLBtGL3tyO2QHNsCvoumwtts--zB3gDbSxSopWo6ECSCb2YNZInM-2sP6TIvwvA8hsNpnnqIw7tPZPUg7OerC7Y_4VSqTGy7IhBuLC6Isff1_C2qaA32lAO0=' }}
  COOKIE_2: ${{ secrets.COOKIE_2 }}
  COOKIE_3: ${{ secrets.COOKIE_3 }}
  COOKIE_4: ${{ secrets.COOKIE_4 }}
  COOKIE_5: ${{ secrets.COOKIE_5 }}
  EMAIL_USER: ${{ secrets.EMAIL_USER }}
  EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
  EMAIL_TO: ${{ secrets.EMAIL_TO }}
  DINGDING_WEBHOOK: ${{ 'https://oapi.dingtalk.com/robot/send?access_token=31a376eea2cc129c92edf03200ef8b7b6ebb5380e29db3c7ac45fbf2c638068d' }}
  PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
  WEIXIN_WEBHOOK: ${{ secrets.WEIXIN_WEBHOOK }}
  SERVERPUSHKEY: ${{ secrets.SERVERPUSHKEY }}

jobs:
  CheckIn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Run Project
        run: |
          cd workflows
          yarn
          yarn checkin
#  SeaGold:
#    needs: CheckIn
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-node@v2
#      - name: Run Project
#        run: |
#          cd workflows
#          yarn
#          yarn seagold
